#! /usr/bin/bash

############################## Setting up the Database ######################################

database="/home/youssefmedhat/DBMS_ITI/databse"

if [[ -e $database ]]
then
        cd $database
else
        mkdir $database
        cd $database
fi

echo "Database is Ready"

########################## Main Menu Functionalities ########################################
#to create a database
create_database() 
{
    read -p "Please Enter Database's Name: " dbName
    if [[ -e $dbName ]]
    then
        echo "Database already exists."
    else
        mkdir $dbName
        echo "Database is created successfully."
    fi
}

#to list databases
list_databases() 
{
    echo "Databases in the system:"
    ls
}
#to connect to database
connect_to_database(){
    PS3=$'\nPlease select a database to connect to: '  
    list_of_dbs=$(ls)  

    select choice in $list_of_dbs  
    do
        if [ -n "$choice" ]; then 
            cd "$choice"  
            echo "You are now connected to $choice."
            
            break
        else
            echo "Invalid choice. Please select a valid database."
        fi
    done
cd $database
PS3=$'\nPlease select an option: '
}
#to drop database
drop_database(){
    PS3=$'\nPlease select a database to drop : '  
    list_of_dbs=$(ls)  
    
    select choice in $list_of_dbs  
    do
        if [ -n "$choice" ]; then 
            rmdir $choice 
            echo "You are dropped table $choice."
            break
        else
            echo "Invalid choice. Please select a valid database."
        fi
    done
cd $database
PS3=$'\nPlease select an option: '
}

########################## Main Menu  ########################################
PS3=$'\nPlease select an option: '
wantsToExit=1
while [[ $wantsToExit -eq 1 ]]
do
	echo -e '<------------------- WELCOME TO THE DATABASE ---------------------> \n'
	select choice in "Create Database" "List Databases" "Connect To Databases" "Drop Database" "Exit"
	do
	    case $choice in
		"Create Database")
		        create_database 
		        break
		    ;;
		"List Databases")
		        list_databases
		        break
		    ;;
		"Connect To Databases")
		    	connect_to_database
		    	break
		    ;;
		"Drop Database")
		    	drop_database
		    	break
		    ;;
		"Exit") 
		    	wantsToExit=0
		    	echo "Exiting..."
		    	break
		    ;;
		*)
		    echo "Invalid choice. Please choose from 1 to 5."
		    ;;
	    esac
	done
done
